### PR TITLE
Add module help tests to Plaster and template

### PR DESCRIPTION
**Pull request by davegreen**
Follow on from PR #141 to add help existence checks to Plaster and the NewModule template.

### CODE REVIEW

**Comment by daviwil** [comment]
Actually, I just realized that we need to think about whether it's good to bring the Help.Tests.ps1 code directly into this project since it is a part of June's project.  Even though she licensed the code in that repo as MIT, since this is a Microsoft licensed project we have to take some extra steps before merging in code from another project.  Let me ask someone about that today before we merge this PR.

**Comment by rkeithhill** [comment]
I briefly hesitated on the `Created with: 	SAPIEN Technologies, Inc., PowerShell Studio 2016 v5.2.119` comment but figured the attribution would be OK.  Although it might be a bit odd seeing this inside a file being edited in VSCode.  ;-)

**Comment by davegreen** [comment]
OK I did check the licensing beforehand and I understand the requirement for that, sounds good. I had a similar reaction to the comment block, it does look at little odd at first, but i thought keeping the attribution is 'better community'.

**Comment by daviwil** [comment]
We definitely want and need attribution on any code that comes from another project, but unfortunately Microsoft open source process dictates that we take some extra steps before integrating things just to make sure we're doing it the "right" way.  In this case it means I need to get quick approval on integrating the code using an internal process.

**Comment by davegreen** [comment]
Sure, I understand the need for it, sorry to cause you an inconvenience!

**Comment by daviwil** [comment]
The process is causing me an inconvenience, your contribution is helping a lot ;)

**Comment by kilasuit** [comment]
@daviwil - there is also perhaps a need for a wider discussion here too other than just the discussion that you need to have on "can we include it" and one of the points that we need to determine is whether is it the right code to include?

This is especially important as it seems that this project is becoming poised to become the "defacto" standard for the module building/creation process and I think that as a wider community we perhaps need to have a small re-evaluation to ensure that we add the right tests in the right way.

Not trying to throw spanner in the works but I do think that this is one of those items that we need to get right and get it right the first time.

**Comment by daviwil** [comment]
@kilasuit I totally agree with you.  How would you like to proceed in getting a review going to make sure that the default template has the right tests, etc for the community?  I'm sure @rkeithhill would be really happy to get more feedback on that before we do a first official release.

**Comment by rkeithhill** [comment]
Keep in mind that the current NewModule template has one Pester test previous to this.  That test simply verifies the module manifest file is valid using Test-ModuleManifest.

**Comment by rkeithhill** [comment]
Also, I think what we put in needs to meet a bar of "the vast majority of users will use this" or the feature doesn't get in the way when not used.  For example, I really like that the Sign task impl in the build script. If you configure the build script with a cert name it will sign but out-of-the-box, that task simply says there is no cert to sign with and moves on.

**Comment by davegreen** [comment]
I'm all for getting more feedback on these kinds of things and what should (and should not) be included to improve the end product. 

My take on the module template is that it could really help others by providing a concise set of community approved feedback in test form for the things that most people would want to be in place for publishing a module to the gallery. The trick is not to go overboard with it.

Using these tests as an example for that, they have really helped me improve my help writing and coverage, by making sure I don't miss a parameter or description on an exported function that users would normally expect help to be present on, but it's not overbearing by making me document things normal users wouldn't necessarily see.

I'm definitely willing to put time into discussing where the line should be for that and use everyones opinions and exoerience to hit the right balance.

**Comment by jdhitsolutions** [comment]
Closing as a potentially obsolete request given the age.

**Pull request closed without merging**
