### PR TITLE
Zloeberdev2

### PR DESCRIPTION
**Pull request by zloeber**
Additional capability for new-plastermanifest that allows both parameters and content to be passed into the function as part of the manifest creation process. This is independent from the 'addcontent' switch as it allows custom strings to be passed in rather than looking for existing xml files. Added additional pester tests to account for the new parameters as well.

### CODE REVIEW

**Comment by zloeber** [comment]
Is this travis integration new? I'm not certain how to rectify this build failure.

**Comment by daviwil** [comment]
The Travis build does nothing at the moment, don't worry about it :)  I probably shouldn't have turned it on so hastily, I'll turn it back off until we're actually using it.

**Comment by PowerSchill** [comment]
You can set it up so that it won't attempt the travis build until we actually have a travis config in the repo.

**Comment by justin-p** [comment]
Hi @daviwil, is there anything preventing this PR form being merged ? If so i would love to take a stab at it.

**Comment by rkeithhill** [comment]
@justin-p David is off working on other things for GitHub (last I heard).  This PR I don't quite get because I'm not sure why you'd want to specify the input to this command using strings containing XML?  You can already add that XML to the generated manifest.  I would think that a PowerShell might prefer to do this instead:
```powershell
New-PlasterManifest ... -AddParameter @{name="ModuleName"; type="text"; prompt="Enter the name of the module. No space, underscores, or special characters are allowed"},@{...}
```
And for files, perhaps:
```
$files = Get-ChildItem .\staging -r -file
New-PlasterManifest ... -AddFile $files
```

**Comment by justin-p** [comment]
Hi @rkeithhill, yeah I get what you mean. Just created a [Draft PR](https://github.com/PowerShell/Plaster/pull/361) that gives the same end result this PR gives only in a more 'PowerShelly'-way.

**Comment by psjamesp** [comment]
Not needed

**Pull request closed without merging**
